name: CI Build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv (+ Python 3.13)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Ruff check
        run: uvx ruff check --output-format=github .
      - name: isort check
        run: uvx isort --check-only .
      - name: Black format check
        run: uvx black --check .
